example_param:
  pits:    pitches c des eisis f g
  accs:    accents _ "" .
  accss:   accentss _ > .,espressivo ! > ^
  dyns:    dynamics p f ""
  dynss:   dynamicss p f pp,sf ff sfz
  durs:    durations 1 2 4. 8 16
  durss:   durationss 1 2 4.,8 16,8 8 8 4
  ints:    intmotto r -3 5 7 r 0
  intss:   intmottos r -3 5 7 r 0,3 2 1 r r
  pitoct:  pitoctpr (c,"'")
  pitocts: pitoctprs (c,"'"),(g,""),(d,",")
  instrument: instrument acoustic grand

example_texture:
  reps: int 20
  voice1:
    instr:  instrument marimba
    key:    key g major
    clef:   clef treble
    scale:  pitches g a b c d e fis
    start:  pitoctpr (g,"''")
  voice2:
    instr:  instrument marimba
    key:    key g major
    clef:   clef treble
    scale:  pitches g a b c d e fis
    start:  pitoctpr (g,"'")
  voice3:
    instr:  instrument marimba
    key:    key g major
    clef:   clef treble
    scale:  pitches g a b c d e fis
    start:  pitoctpr (d,"'")
  voice4:
    instr:  instrument marimba
    key:    key g major
    clef:   clef treble
    scale:  pitches g a b c d e fis
    start:  pitoctpr (d,"'")
  voice5:
    instr:  instrument marimba
    key:    key g major
    clef:   clef bass
    scale:  pitches g a b c d e fis
    start:  pitoctpr (g,"")
  voice6:
    instr:  instrument marimba
    key:    key g major
    clef:   clef bass
    scale:  pitches g a b c d e fis
    start:  pitoctpr (g,",")
  intss:    intmottos r -1 1 1 1 -1,1 -2 1 -2 1 r,0 0 2 0 0 -2
  durss:    durationss 8 8 4 8. 16 8 8,8 16 16 16 16 8 8,8. 16 16 16 8 16 16
  accss:    accentss ^ ~ ^ - . ~ .,~ > ~ > ~ > ~,> > ~ ~ > > ~
  dynss:    dynamicss ff ~ ~ ~ pp ~ ~,mf ~ mp ~ f ~ ff,p ~ ~ ~ mp ~ mf

  