example_param:
  pits:    pitches c des eisis f g
  accs:    accents _ "" .
  accss:   accentss _ > .,espressivo ! > ^
  dyns:    dynamics p f ""
  dynss:   dynamicss p f pp,sf ff sfz
  durs:    durations 1 2 4. 8 16
  durss:   durationss 1 2 4.,8 16,8 8 8 4
  ints:    intmotto r -3 5 7 r 0
  intss:   intmottos r -3 5 7 r 0,3 2 1 r r
  pitoct:  pitoctpr (c,"'")
  pitocts: pitoctprs (c,"'"),(g,""),(d,",")
  instrument: instrument acoustic grand

example_texture:
  reps: int 20
  voice1:
    instr:  instrument marimba
    key:    key g major
    clef:   clef treble
    scale:  pitches g a b c d e fis
    start:  pitoctpr (d,"''")
  voice2:
    instr:  instrument marimba
    key:    key g major
    clef:   clef treble
    scale:  pitches g a b c d e fis
    start:  pitoctpr (b,"'")
  voice3:
    instr:  instrument marimba
    key:    key g major
    clef:   clef treble
    scale:  pitches g a b c d e fis
    start:  pitoctpr (g,"'")
  voice4:
    instr:  instrument marimba
    key:    key g major
    clef:   clef bass
    scale:  pitches g a b c d e fis
    start:  pitoctpr (e,"")
  voice5:
    instr:  instrument marimba
    key:    key g major
    clef:   clef bass
    scale:  pitches g a b c d e fis
    start:  pitoctpr (g,"")
  voice6:
    instr:  instrument marimba
    key:    key g major
    clef:   clef bass
    scale:  pitches g a b
    start:  pitoctpr (g,",")
  intss:    intmottos r -3 5 -1 r -1,3 2 -2 r r -3,2 -2 5 -5 2 0 1 0 -3 0
  durss:    durationss 8 8 4 8. 16 4,2 16 16 16 16 4,8. 16 16 16 8 16 16 8
  accss:    accentss ^ ~ ~ - . ~,- ~ ^ . ^ .,> > ~ ~ > > ~ ~
  dynss:    dynamicss ff ~ ~ pp ~ ~,p ~ mp ~ f ~,pp ~ p ~ mp ~ mf ~

  