# Can parser parse all param types?
example_param:
  pits:    (c,des,eisis,f,g)
  accs:    (_,~,.)
  accss:   ((_,>,.),(espressivo,!,>,^))
  dyns:    (p,f,~)
  dynss:   ((p,f,pp),(sf,ff,sfz))
  durs:    (1,2,4.,8,16)
  durss:   ((1,2,4.),(8,16),(8,8,8,4))
  ints:    (r,-3,5,7,r,1)
  intss:   ((r,-3,5,7,r,1),(3,2,1,r,r))
  pitoct:  (c,0)
  pitocts: ((c,0),(g,-1),(d,-2))
  instrument: acoustic grand

example_texture:
  reps: int 10
  voice1:
    instr:  marimba
    key:    g major
    clef:   treble
    scale:  (g,a,b,c,d,e,fis)
    start:  (g,1)
  voice2:
    instr:  marimba
    key:    g major
    clef:   treble
    scale:  (g,a,b,c,d,e,fis)
    start:  (g,0)
  voice3:
    instr:  marimba
    key:    g major
    clef:   bass
    scale:  (g,a,b,c,d,e,fis)
    start:  (g,-1)
  voice4:
    instr:  marimba
    key:    g major
    clef:   bass
    scale:  (g,a,b,c,d,e,fis)
    start:  (g,-2)
  intss:    ((r,-2,2,2,2,-2),(2,-3,2,-3,2,-3,r),(1,1,3,1,1,-3,6,-3),(1,2,2,4,2,-3,-5,3,3,3))
  durss:    ((8,8,4,8.,16,8,8),(8,16,16,16,16,8,8,8),(8.,16,16,16,8,16,16,16,16),(16,16,16,16,16,8.,16,16,16,16))
  accss:    ((^,~,^,-,.,~,.),(~,>,~,>,~,>,~),(>,>,~,~,>,>,~),(~,~,~,~,>,~))
  dynss:    ((ff,~,~,~,pp,~,~),(mf,~,mp,~,f,~,ff),(p,~,~,~,mp,~,mf),(f,~,~,~,~,~,~))

example_arpeggios:
  voice1:
    instr:   acoustic grand
    key:     c major
    scale:   (c,d,e,f,g,a,b)
    ranges:  (((c,-2),(c,3)),((c,3),(c,-2)))
  voice2:
    instr:   acoustic grand
    key:     c major
    scale:   (c,d,e,f,g,a,b)
    ranges:  (((c,-2),(c,2)),((c,2),(c,-2)))
  intss:     ((1,r,1,3),(1,r,1,-3))
  durss:     ((8,8,8,8),(8,8,8,8))
  accss:     ((~,~,~,~),(~,~,~,~))
  dynss:     ((p,~,f,~),(f,~,p,~))
  slurss:    ((~,~,~,~),(~,~,~,~))

# lilypond bug: last time signature wins, all piano-staff voices
#               have that time signature
example_swirls:
  voice1:
    instr:   acoustic grand
    key:     c major
    time:    ((2,2,3),(7,8))
    scale:   (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
    mpitss:  ((a,fis,e,b,d,dis,ais,g,g,ais),(c,g,d,d,a,dis,r,d),(f,g,a,dis,e,fis,c,b,r,b,r,b))
    durs:    (4,8,8,4,8,8,8)
    accents: (~,~,>,>,~,~,~,~)
    range:   ((c,-3),(c,3))
    ghosts:  ((3,4),(2,5))
  voice2:
    instr:   acoustic grand
    key:     c major
    time:    ((2,2,3),(7,8))
    scale:   (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
    mpitss:  ((a,fis,e,b,d,dis,ais,g,g,ais),(c,g,d,d,a,dis,r,d),(f,g,a,dis,e,fis,c,b,r,b,r,b))
    durs:    (4,8,8,8,4,8,8)
    accents: (~,>,~,>,>,~)
    range:   ((c,-3),(c,3))
    ghosts:  ((10,5),(2,10))
  voice3:
    instr:   acoustic grand
    key:     c major
    time:    ((2,2,3),(7,8))
    scale:   (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
    mpitss:  ((a,fis,e,b,d,dis,ais,g,g,ais),(c,g,d,d,a,dis,r,d),(f,g,a,dis,e,fis,c,b,r,b,r,b))
    durs:    (4,8,4,16,16,8,4)
    accents: (~,>,>,>,>,~,~,~)
    range:   ((c,-3),(c,3))
    ghosts:  ((3,7),(1,4))
#   mpitss:  ((c,dis,dis,dis,e,d,r,cis,e),(c,g,d,d,a,dis,r,d),(cis,d,r,fis,a,r,e,f))
