example_param:
  pits:    pitches c,des,eisis,f,g
  accs:    accents _,~,.
  accss:   accentss _,>,.;espressivo,!,>,^
  dyns:    dynamics p,f,~
  dynss:   dynamicss p,f,pp;sf,ff,sfz
  durs:    durations 1,2,4.,8,16
  durss:   durationss 1,2,4.;8,16;8,8,8,4
  ints:    intmotto r,-3,5,7,r,0
  intss:   intmottos r,-3,5,7,r,0;3,2,1,r,r
  pitoct:  pitoctpr (c,0)
  pitocts: pitoctprs (c,0),(g,-1),(d,-2)
  instrument: instrument acoustic grand

example_texture:
  reps: int 20
  voice1:
    instr:  instrument marimba
    key:    key g major
    clef:   clef treble
    scale:  pitches g,a,b,c,d,e,fis
    start:  pitoctpr (g,1)
  voice2:
    instr:  instrument marimba
    key:    key g major
    clef:   clef treble
    scale:  pitches g,a,b,c,d,e,fis
    start:  pitoctpr (g,0)
  voice3:
    instr:  instrument marimba
    key:    key g major
    clef:   clef treble
    scale:  pitches g,a,b,c,d,e,fis
    start:  pitoctpr (d,0)
  voice4:
    instr:  instrument marimba
    key:    key g major
    clef:   clef treble
    scale:  pitches g,a,b,c,d,e,fis
    start:  pitoctpr (d,0)
  voice5:
    instr:  instrument marimba
    key:    key g major
    clef:   clef bass
    scale:  pitches g,a,b,c,d,e,fis
    start:  pitoctpr (g,-2)
  voice6:
    instr:  instrument marimba
    key:    key g major
    clef:   clef bass
    scale:  pitches g,a,b,c,d,e,fis
    start:  pitoctpr (g,-2)
  intss:    intmottos r,-1,1,1,1,-1;1,-2,1,-2,1,r;0,0,2,0,0,-2
  durss:    durationss 8,8,4,8.,16,8,8;8,16,16,16,16,8,8;8.,16,16,16,8,16,16
  accss:    accentss ^,~,^,-,.,~,.;~,>,~,>,~,>,~;>,>,~,~,>,>,~
  dynss:    dynamicss ff,~,~,~,pp,~,~;mf,~,mp,~,f,~,ff;p,~,~,~,mp,~,mf
