# Can parser parse all param types?
example_param:
  pits:    (c,des,eisis,f,g)
  accs:    (_,~,.)
  accss:   ((_,>,.),(espressivo,!,>,^))
  dyns:    (p,f,~)
  dynss:   ((p,f,pp),(sf,ff,sfz))
  durs:    (1,2,4.,8,16)
  durss:   ((1,2,4.),(8,16),(8,8,8,4))
  ints:    (r,-3,5,7,r,1)
  intss:   ((r,-3,5,7,r,1),(3,2,1,r,r))
  pitoct:  (c,0)
  pitocts: ((c,0),(g,-1),(d,-2))
  instrument: acoustic grand

maxrand_texture:
  reps: int 10
  common:
    score: example_maxrand
  voice1:
    instr:  marimba
    key:    g major
    clef:   treble
    scale:  (g,a,b,c,d,e,fis)
    start:  (g,1)
  voice2:
    instr:  marimba
    key:    g major
    clef:   treble
    scale:  (g,a,b,c,d,e,fis)
    start:  (g,0)
  voice3:
    instr:  marimba
    key:    g major
    clef:   bass
    scale:  (g,a,b,c,d,e,fis)
    start:  (g,-1)
  voice4:
    instr:  marimba
    key:    g major
    clef:   bass
    scale:  (g,a,b,c,d,e,fis)
    start:  (g,-2)
  intss:    ((r,-2,2,2,2,-2),(2,-3,2,-3,2,-3,r),(1,1,3,1,1,-3,6,-3),(1,2,2,4,2,-3,-5,3,3,3))
  durss:    ((8,8,4,8.,16,8,8),(8,16,16,16,16,8,8,8),(8.,16,16,16,8,16,16,16,16),(16,16,16,16,16,8.,16,16,16,16))
  accss:    ((^,~,^,-,.,~,.),(~,>,~,>,~,>,~),(>,>,~,~,>,>,~),(~,~,~,~,>,~))
  dynss:    ((ff,~,~,~,pp,~,~),(mf,~,mp,~,f,~,ff),(p,~,~,~,mp,~,mf),(f,~,~,~,~,~,~))

arpeggios_texture:
  common:
    score: example_arpeggios
  voice1:
    instr:   acoustic grand
    key:     c major
    scale:   (c,d,e,f,g,a,b)
    ranges:  (((c,-2),(c,3)),((c,3),(c,-2)))
  voice2:
    instr:   acoustic grand
    key:     c major
    scale:   (c,d,e,f,g,a,b)
    ranges:  (((c,-2),(c,2)),((c,2),(c,-2)))
  intss:     ((1,r,1,3),(1,r,1,-3))
  durss:     ((8,8,8,8),(8,8,8,8))
  accss:     ((~,~,~,~),(~,~,~,~))
  dynss:     ((p,~,f,~),(f,~,p,~))
  slurss:    ((~,~,~,~),(~,~,~,~))
