# 
# Sample configurations
#

voicemix:
  common:
    changeclefs: int 3
    tempo:       int 120
    key:         c major
    instr:       acoustic grand
    time:        (4,4)
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
  section1:
    stype:   neutral
    reps:    int 1
    voice1:
      vtype:    xpose
      durss:    ((8),(8.,16,16))
      accentss: ((>,~),(~,>))
      mpitOctss: (((c,0),(dis,0),(r,0),(gis,0),(d,0)),((dis,0),(r,0),(c,0),(gis,0),(d,0),(e,0)))
      range:     ((c,-2),(c,2))
    voice2:
      vtype:    xpose
      range:   ((c,2),(c,-2))
      mpitOctss: (((a,0),(g,0),(dis,0),(r,0),(gis,-1)),((a,0),(g,0),(r,0),(r,0),(dis,0),(gis,-1)))
      durss:    ((8,16,16),(8.,16),(8,8,8))
      accentss: ((>,~,~))
    voice3:
      vtype:     repeat
      mpitOctss: (((a,0),(g,0),(dis,0),(r,0),(gis,-1)),((a,0),(g,0),(r,0),(r,0),(dis,0),(gis,-1)))
      durss:     ((16,8.))
      accentss:  ((~,>,>),(>,>,~,~,~))
      register:  (g,-1)
      durval:    int 1024

canon:
  common:
    tempo:       int 100
    key:         c major
    changeclefs: int 3
    instr:       acoustic grand
    time:        (4,4)
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
    register:    (c,0)
    accentss:    ((>,>,~,~),(~,>,>),(>,>,>,>))
    durss:       ((8),(16,16),(4),(8,8),(16,16,16,16))
    mpitOctss:   (((b,0),(e,0),(a,0),(d,0),(r,0),(g,0),(c,0),(f,0),(ais,0),(cis,0),(r,0),(dis,0),(fis,0),(gis,0)),
                  ((b,0),(e,0),(r,0),(a,0),(d,0),(g,0),(c,0),(f,0),(ais,0),(cis,0),(dis,0),(r,0),(fis,0),(gis,0)))
  section1:
    stype:        fadein
    delays:       (3,0,2,1)
    fadeInAcc1:   .
    fadeInAcc2:   !
    fadeInDyn1:   mf
    fadeInDyn2:   p
    norrsmods:    (fadeInAccs,fadeInDyns)
    common:
      vtype:     canon
      durval:    int 512
      accentss:  ((~,~,~))
    voice1:
      rotval:    int 0
    voice2:
      rotval:    int 3
    voice3:
      rotval:    int 7
    voice4:
      rotval:    int 10
  section2:
    stype:      neutral
    reps:       int 4
    cfgmods:    (incrRandOcts)
    uniformAcc: !
    uniformDyn: f
    sectionDyns: (mf,f,ff,f)
    norrsmods:  (uniformAccs,sectionDyns)
    common:
      vtype:    canon
      durval:   int 512
    voice1:
      rotval:   int 0
    voice2:
      rotval:   int 3
    voice3:
      rotval:   int 7
    voice4:
      rotval:   int 10
  section3:
    stype:       fadeout
    drops:       (3,0,2,1)
    cfgmods:     (decrRandOcts)
    uniformAcc:  ! 
    sectionDyns: (mf,mp,p,ppp)
    norrsmods:   (uniformAccs,sectionDyns)
    common:
      vtype:    canon
      durval:   int 512
    voice1:
      rotval:   int 0
    voice2:
      rotval:   int 3
    voice3:
      rotval:   int 7
    voice4:
      rotval:   int 10

bridge:
  common:
    tempo:       int 120
    key:         c major
    changeclefs: int 3
    instr:       acoustic grand
    time:        ((2,2,3),(7,8))
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
    vtype:       xpose
  section1:
    stype: neutral
    reps:  int 1
    uniformAcc: !
    uniformDyn: mp
    norrsmods:  (uniformAccs,uniformDyns)
    common:
      mpitOctss: (((c,0),(dis,0),(r,0),(gis,0),(d,0)),((dis,0),(r,0),(c,0),(gis,0),(d,0),(e,0)))
      range:     ((c,-2),(c,2))
    voice1:
      durss:    ((4,8,8,4),(8,8,8),(8,16,16,8),(4,16,16,8,4))
      accentss: ((~,~,>,>),(~,~,~,~))
    voice2:
      durss:    ((4,8,8),(8,4,8,8),(8,4,8,8),(4,8,16,16))
      accentss: ((~,>,~),(>,>,~))
    voice3:
      durss:    ((4,8,4),(16,16,8,4),(4,8,4),(4,8,4))
      accentss: ((~,>,>),(>,>,~,~,~))
    voice4:
      durss:    ((4,8,4),(16,16,8,4),(4,4,8))
      accentss: ((~,>,>),(>,>,~,~,~))
  section2:
    stype: neutral
    reps:  int 1
    uniformAcc: .
    uniformDyn: f
    norrsmods:  (uniformAccs,uniformDyns)
    common:
      range:   ((c,2),(c,-2))
      mpitOctss: (((a,0),(g,0),(dis,0),(r,0),(gis,-1)),((a,0),(g,0),(r,0),(r,0),(dis,0),(gis,-1)))
    voice1:
      durss:    ((8,8,16),(16,8,8))
      accentss: ((~,~,>,>),(~,~,~,~))
    voice2:
      durss:    ((16,16,16),(8,16,16,8))
      accentss: ((~,>,~),(>,>,~))
    voice3:
      durss:    ((16,16),(8,8))
      accentss: ((~,>,>),(>,>,~,~,~))
    voice4:
      durss:    ((16,16,16,16))
      accentss: ((~,>,>),(>,>,~,~,~))
  
  