# Sketches

canon:
  common:
    tempo:       int 100
    key:         c major
    changeclefs: int 3
    instr:       acoustic grand
    time:        (4,4)
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
    register:    (c,0)
    accentss:    ((>,>,~,~),(~,>,>),(>,>,>,>))
    durss:       ((8),(16,16),(4),(8,8),(16,16,16,16))
    mPitOctsss:  (((b,0),(e,0),(a,0),(d,0),r,(g,0),(c,0),(f,0),(ais,0),(cis,0),r,(dis,0),(fis,0),(gis,0)),
                  ((b,0),(e,0),r,(a,0),(d,0),(g,0),(c,0),(f,0),(ais,0),(cis,0),(dis,0),r,(fis,0),(gis,0)))
  section1:
    stype:        fadein
    delays:       (3,0,2,1)
    fadeInAcc1:   .
    fadeInAcc2:   !
    fadeInDyn1:   mf
    fadeInDyn2:   p
    norrsmods:    (fadeInAccs,fadeInDyns)
    common:
      vtype:     canon
      durval:    int 512
      accentss:  ((~,~,~))
    voice1:
      rotval:    int 0
    voice2:
      rotval:    int 3
    voice3:
      rotval:    int 7
    voice4:
      rotval:    int 10
  section2:
    stype:      neutral
    reps:       int 4
    cfgmods:    (incrRandOcts)
    uniformAcc: !
    uniformDyn: f
    sectionDyns: (mf,f,ff,f)
    norrsmods:  (uniformAccs,sectionDyns)
    common:
      vtype:    canon
      durval:   int 512
    voice1:
      rotval:   int 0
    voice2:
      rotval:   int 3
    voice3:
      rotval:   int 7
    voice4:
      rotval:   int 10
  section3:
    stype:       fadeout
    drops:       (3,0,2,1)
    cfgmods:     (decrRandOcts)
    uniformAcc:  ! 
    sectionDyns: (mf,mp,p,ppp)
    norrsmods:   (uniformAccs,sectionDyns)
    common:
      vtype:    canon
      durval:   int 512
    voice1:
      rotval:   int 0
    voice2:
      rotval:   int 3
    voice3:
      rotval:   int 7
    voice4:
      rotval:   int 10

bridge:
  common:
    tempo:       int 120
    key:         c major
    changeclefs: int 3
    instr:       acoustic grand
    time:        ((2,2,3),(7,8))
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
  section1a:
    stype: neutral
    reps:  int 1
    uniformAcc: !
    uniformDyn: mp
    norrsmods:  (uniformAccs,uniformDyns)
    common:
      # these are two choices from (c,0) to (d,0) and (dis,0) to (e,0),
      # so that's pretty close, whole step up, then half-step up
      mPitOctsss: (((c,0),(dis,0),r,(gis,0),(d,0)),((dis,0),r,(c,0),(gis,0),(d,0),(e,0)))
      range:      ((c,-2),(c,2)))
      vtype:      xpose
    voice1:
      # trick here is for duration choices to be equal in duration
      # and for total counts of durs to be as close as possible
      # count of elements in durs: 15 -> 19 -> 18
      durss:    ((4,8,8),(16,16,16,8,16,16,16),(4,16,16,8),(8,8,8,8))
      accentss: ((~,~,>,>),(~,~,~,~))
    voice2:
      # count of elements in durs: 13 -> 16
      durss:    ((4,8,8),(8,16,8,16,8),(16,16,4,16,16),(8,4,8))
      accentss: ((~,>,~),(>,>,~))
    voice3:
      # count of elements in durs: 20 -> 16
      durss:    ((4,8,16,16),(8,4,8),(4,8.,16),(16,8,16,16,8,16))
      accentss: ((~,>,>),(>,>,~,~,~))
    voice4:
      # count of elements in durs: 18 -> 16
      durss:    ((4,8,16,16),(8,16,4,16),(8,16,8,16,8),(8,8,4))
      accentss: ((~,>,>),(>,>,~,~,~))
  section1b:
    stype: neutral
    reps:  int 1
    uniformAcc: !
    uniformDyn: mp
    norrsmods:  (uniformAccs,uniformDyns)
    common:
      # these are two choices from (c,0) to (d,0) and (dis,0) to (e,0),
      # so that's pretty close, whole step up, then half-step up
      mPitOctsss: (((c,0),(dis,0),r,(gis,0),(f,0)),((dis,0),r,(c,0),(gis,0),(d,0),(a,0)))
      range:      ((g,-2),(g,2)))
      vtype:      xpose
    voice1:
      # trick here is for duration choices to be equal in duration
      # and for total counts of durs to be as close as possible
      # count of elements in durs: 15 -> 19 -> 18
      durss:    ((4,8,8),(16,16,16,8,16,16,16),(4,16,16,8),(8,8,8,8))
      accentss: ((~,~,>,>),(~,~,~,~))
    voice2:
      # count of elements in durs: 13 -> 16
      durss:    ((4,8,8),(8,16,8,16,8),(16,16,4,16,16),(8,4,8))
      accentss: ((~,>,~),(>,>,~))
    voice3:
      # count of elements in durs: 20 -> 16
      durss:    ((4,8,16,16),(8,4,8),(4,8.,16),(16,8,16,16,8,16))
      accentss: ((~,>,>),(>,>,~,~,~))
    voice4:
      # count of elements in durs: 18 -> 16
      durss:    ((4,8,16,16),(8,16,4,16),(8,16,8,16,8),(8,8,4))
      accentss: ((~,>,>),(>,>,~,~,~))
  section2:
    stype: neutral
    reps:  int 1
    uniformAcc: .
    uniformDyn: f
    norrsmods:  (uniformAccs,uniformDyns)
    common:
      range:      ((c,2),(c,-2))
      mPitOctsss: (((a,0),(g,0),(dis,0),r,(gis,-1)),((g,0),(a,0),r,r,(dis,0),(gis,-1)))
      vtype:      xpose
    voice1:
      durss:    ((8,8,16),(16,8,8))
      accentss: ((~,~,>,>),(~,~,~,~))
    voice2:
      durss:    ((16,16,16),(8,16,16,16,8))
      accentss: ((~,>,~),(>,>,~))
    voice3:
      durss:    ((16,16,8),(8,16,16,8))
      accentss: ((~,>,>),(>,>,~,~,~))
    voice4:
      durss:    ((16,16,16,16),(8,16,16,8))
      accentss: ((~,>,>),(>,>,~,~,~))
  section3:
    stype: neutral
    reps:  int 1
    uniformAcc: !
    uniformDyn: mp
    norrsmods:  (uniformAccs,uniformDyns)
    common:
      mPitOctsss: (((c,0),(dis,0),r,(gis,0),(f,0)),((e,0),r,(c,0),(gis,0),(d,0),(a,0)))
      range:      ((c,-1),(g,2))
      vtype:      xpose
    voice1:
      durss:    ((4,8,8),(16,16,16,8,16,16,16),(4,16,16,8),(8,8,8,8))
      accentss: ((~,~,>,>),(~,~,~,~))
    voice2:
      durss:    ((4,8,8),(8,16,8,16,8),(16,16,4,16,16),(8,4,8))
      accentss: ((~,>,~),(>,>,~))
    voice3:
      durss:    ((4,8,16,16),(8,4,8),(4,8.,16),(16,8,16,16,8,16))
      accentss: ((~,>,>),(>,>,~,~,~))
    voice4:
      durss:    ((4,8,16,16),(8,16,4,16),(8,16,8,16,8),(8,8,4))
      accentss: ((~,>,>),(>,>,~,~,~))
  section4:
    stype: neutral
    reps:  int 1
    uniformAcc: .
    uniformDyn: f
    norrsmods:  (uniformAccs,uniformDyns)
    common:
      range:      ((c,2),(c,-2))
      mPitOctsss: (((g,0),(f,0),(dis,0),r,(gis,-1)),((dis,0),(g,0),r,r,(f,0),(gis,-1)))
      vtype:      xpose
    voice1:
      durss:    ((4,8,8),(16,16,16,8,16,16,16),(4,16,16,8),(8,8,8,8))
      accentss: ((~,~,>,>),(~,~,~,~))
    voice2:
      durss:    ((4,8,8),(8,16,8,16,8),(16,16,4,16,16),(8,4,8))
      accentss: ((~,>,~),(>,>,~))
    voice3:
      durss:    ((4,8,16,16),(8,4,8),(4,8.,16),(16,8,16,16,8,16))
      accentss: ((~,>,>),(>,>,~,~,~))
    voice4:
      durss:    ((4,8,16,16),(8,16,4,16),(8,16,8,16,8),(8,8,4))
      accentss: ((~,>,>),(>,>,~,~,~))
  section5:
    stype: neutral
    reps:  int 2
    uniformAcc: .
    uniformDyn: ff
    norrsmods:  (uniformAccs,uniformDyns)
    common:
      range:      ((c,1),(g,-2))
      mPitOctsss: (((f,0),(e,0),(dis,0),r,(gis,-1)),((dis,0),(f,0),r,(e,0),(gis,-1)))
      vtype:      xpose
    voice1:
      durss:    ((4,8,8),(16,16,16,8,16,16,16),(4,16,16,8),(8,8,8,8))
      accentss: ((~,~,>,>),(~,~,~,~))
    voice2:
      durss:    ((4,8,8),(8,16,8,16,8),(16,16,4,16,16),(8,4,8))
      accentss: ((~,>,~),(>,>,~))
    voice3:
      durss:    ((4,8,16,16),(8,4,8),(4,8.,16),(16,8,16,16,8,16))
      accentss: ((~,>,>),(>,>,~,~,~))
    voice4:
      durss:    ((4,8,16,16),(8,16,4,16),(8,16,8,16,8),(8,8,4))
      accentss: ((~,>,>),(>,>,~,~,~))
  section6:
    stype: neutral
    reps:  int 4
    uniformAcc: .
    sectionDyns: (fff,ff,f,mf)
    norrsmods:  (uniformAccs,sectionDyns)
    common:
      range:      ((c,0),(g,-2))
      mPitOctsss: (((e,0),((d,0),(ais,-1)),r,(gis,-1)),((d,0),r,((e,0),(c,0)),(gis,-1)))
      vtype:      xpose
    voice1:
      durss:    ((16,16,16,16,8,8),(16,16,16,8,16,16,16),(4,16,16,8),(8,8,8,8))
      accentss: ((~,~,>,>),(~,~,~,~))
    voice2:
      durss:    ((4,8,8),(8,16,8,16,8),(16,16,4,16,16),(8,16,16,16,16,8))
      accentss: ((~,>,~),(>,>,~))
    voice3:
      durss:    ((4,8,16,16),(8,16,16,16,16,8),(4,8.,16),(16,8,16,16,8,16))
      accentss: ((~,>,>),(>,>,~,~,~))
    voice4:
      durss:    ((4,8,16,16),(8,16,4,16),(8,16,8,16,8),(8,8,16,16,16,16))
      accentss: ((~,>,>),(>,>,~,~,~))
  section7:
    stype: neutral
    reps:  int 20
    uniformAcc: !
    uniformDyn: pppp
    norrsmods:  (uniformAccs,uniformDyns)
    common:
    # range:      ((g,-1),(g,-2))
      mPitOctsss: ((((d,0),(ais,-1)),((c,0),(gis,-1)),(gis,-1)),(((dis,0),(b,-1)),(cis,0),((gis,-1),(e,-1))))
      vtype:      canon
      durval:     int 64
    # vtype:      xpose
    voice1:
      rotval:   int 0
      register: (c,0)
      durss:    ((16,16,16,16,8,8))
      accentss: ((~,~,>,>),(~,~,~,~))
    voice2:
      rotval:   int 1
      register: (g,-1)
      durss:    ((8,16,8,16,8))
      accentss: ((~,>,~),(>,>,~))
    voice3:
      rotval:   int 2
      register: (e,-1)
      durss:    ((8,16,16,16,16,8))
      accentss: ((~,>,>),(>,>,~,~,~))
    voice4:
      rotval:   int 0
      register: (c,-1)
      durss:    ((8,8,16,16,16,16))
      accentss: ((~,>,>),(>,>,~,~,~))

# heterogonous texture with voices of different types (proof of concept, not even a sketch)
voicemix:
  common:
    changeclefs: int 3
    tempo:       int 120
    key:         c major
    instr:       acoustic grand
    time:        (4,4)
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
  section1:
    stype:   neutral
    reps:    int 1
    voice1:
      vtype:      xpose
      durss:      ((8),(8.,16,16))
      accentss:   ((>,~),(~,>))
      mPitOctsss: (((c,0),(dis,0),r,(gis,0),(d,0)),((dis,0),r,(c,0),(gis,0),(d,0),(e,0)))
      range :     ((c,-2),(c,2))
    voice2:
      vtype:      xpose
      range:      ((c,2),(c,-2))
      mPitOctsss: (((a,0),(g,0),(dis,0),r,(gis,-1)),((a,0),(g,0),r,r,(dis,0),(gis,-1)))
      durss:      ((8,16,16),(8.,16),(8,8,8))
      accentss:   ((>,~,~))
    voice3:
      vtype:      repeat
      mPitOctsss: (((a,0),(g,0),(dis,0),r,(gis,-1)),((a,0),(g,0),r,r,(dis,0),(gis,-1)))
      durss:      ((16,8.))
      accentss:   ((~,>,>),(>,>,~,~,~))
      register:   (g,-1)
      durval:     int 1024

# trial:  first pass without param to tie voices together
homophony:
  common:
    tempo:       int 100
    key:         c major
    changeclefs: int 3
    instr:       acoustic grand
    time:        (4,4)
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
    register:    (c,0)
    accentss:    ((>,>,~,~),(~,>,>),(>,>,>,>))
    durss:       ((8),(16,16),(4),(8,8),(16,16,16,16))
    mPitOctsss:  (((b,0),(e,0),(a,0),(d,0),r,(g,0),(c,0),(f,0),(ais,0),(cis,0),r,(dis,0),(fis,0),(gis,0)),
                  ((b,0),(e,0),r,(a,0),(d,0),(g,0),(c,0),(f,0),(ais,0),(cis,0),(dis,0),r,(fis,0),(gis,0)))
  section:
    stype:      homophony
    reps:       int 4
    uniformAcc: !
    uniformDyn: mp
    norrsmods:  (uniformAccs,uniformDyns)
    common:
      vtype:    canon
      durval:   int 512
    voice1:
      rotval:   int 0
    voice2:
      rotval:   int 0
    voice3:
      rotval:   int 0
    voice4:
      rotval:   int 0

# expand mpitOcts to allow for chords, durss to allow for tuplets
experimental:
  common:
    tempo:       int 100
    key:         c major
    changeclefs: int 3
    instr:       acoustic grand
    time:        (4,4)
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
    register:    (c,0)
    accentss:    ((>,>,~,~),(~,>,>),(>,>,>,>))
  section:
    stype:      homophony
    reps:       int 1
    common:
      vtype:      repeat
      durval:     int 512
      reps:       1
      mPitOctsss: (((b,0),r,((a,0),(f,0))))
      durss:      ((8),(16,16),(4),(8,(3,2,8,(16,8,16,16,16)),4)))
    voice1:
    voice2:
    voice3:
    voice4:
