# Sketches

blend:
  common:
    tempo:       (100,4)
    key:         c major
    changeclefs: int 3
    instr:       acoustic grand
    time:        (4,4)
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
  group:
    grtype:  neutral
    section1:
      stype:        fadecells
      reps:         int 4
      common:
        vtype:     cell
        durval:    int 1536
      voice1:
        mPitOctsss:  (((c,0),(e,0)),((g,0),(b,0)))
        durss:       ((4,4),(4,4))
        accentss:    ((>,>),(.,.))
      voice2:
        mPitOctsss:  (((c,0),(e,0)),((g,0),(b,0)))
        durss:       ((4,4),(4,4))
        accentss:    ((>,>),(!,!))
      voice3:
        mPitOctsss:  (((c,0),(g,0)),((e,0),(b,0)))
        durss:       ((4,4),(4,4))
        accentss:    ((>,>),(-,-))
      voice4:
        mPitOctsss:  (((b,-1),(g,-1)),((e,-1),(c,-1)))
        durss:       ((8,8,8,8),(8,8,8,8))
        accentss:    ((>,~,>,~),(>,~,>,~))
      voice5:
        mPitOctsss:  (((b,-1),(g,-1)),((e,-1),(c,-1)))
        durss:       ((8,8,8,8),(8,8,8,8))
        accentss:    ((>,~,>,~),(>,~,>,~))
      voice6:
        mPitOctsss:  (((b,-1),(e,-1)),((g,-1),(c,-1)))
        durss:       ((8,8,8,8),(8,8,8,8))
        accentss:    ((>,!,>,!),(>,!,>,!))

canon:
  common:
    tempo:       (100,4)
    key:         c major
    changeclefs: int 3
    instr:       acoustic grand
    time:        (4,4)
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
    register:    (c,0)
    accentss:    ((>,>,~,~),(~,>,>),(>,>,>,>))
    durss:       ((8),(16,16),(4),(8,8),(16,16,16,16))
    mPitOctsss:  (((b,0),(e,0),(a,0),(d,0),r,(g,0),(c,0),(f,0),(ais,0),(cis,0),r,(dis,0),(fis,0),(gis,0)),((b,0),(e,0),r,(a,0),(d,0),(g,0),(c,0),(f,0),(ais,0),(cis,0),(dis,0),r,(fis,0),(gis,0)))
  group1:
    grtype:  neutral
    section1:
      stype:        fadein
      delays:       (3,0,2,1)
      fadeInAcc1:   .
      fadeInAcc2:   !
      fadeInDyn1:   mf
      fadeInDyn2:   p
      vesmods:      (fadeInAccs,fadeInDyns)
      common:
        vtype:     canon
        durval:    int 512
        accentss:  ((~,~,~))
      voice1:
        rotval:    int 0
      voice2:
        rotval:    int 3
      voice3:
        rotval:    int 7
      voice4:
        rotval:    int 10
    section2:
      stype:      neutral
      reps:       int 4
      cfgmods:    (incrRandOcts)
      uniformAcc: !
      uniformDyn: f
      sectionDyns: (mf,f,ff,f)
      vesmods:    (uniformAccs,sectionDyns)
      common:
        vtype:    canon
        durval:   int 512
      voice1:
        rotval:   int 0
      voice2:
        rotval:   int 3
      voice3:
        rotval:   int 7
      voice4:
        rotval:   int 10
    section3:
      stype:       fadeout
      drops:       (3,0,2,1)
      cfgmods:     (decrRandOcts)
      uniformAcc:  ! 
      sectionDyns: (mf,mp,p,ppp)
      vesmods:     (uniformAccs,sectionDyns)
      common:
        vtype:    canon
        durval:   int 512
      voice1:
        rotval:   int 0
      voice2:
        rotval:   int 3
      voice3:
        rotval:   int 7
      voice4:
        rotval:   int 10
  
# heterogonous texture with voices of different types (proof of concept, not even a sketch)
voicemix:
  common:
    changeclefs: int 3
    tempo:       (120,4)
    key:         c major
    instr:       acoustic grand
    time:        (4,4)
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
  section1:
    stype:   neutral
    reps:    int 1
    voice1:
      vtype:      xpose
      durss:      ((8),(8.,16,16))
      accentss:   ((>,~),(~,>))
      mPitOctsss: (((c,0),(dis,0),r,(gis,0),(d,0)),((dis,0),r,(c,0),(gis,0),(d,0),(e,0)))
      range :     ((c,-2),(c,2))
    voice2:
      vtype:      xpose
      range:      ((c,2),(c,-2))
      mPitOctsss: (((a,0),(g,0),(dis,0),r,(gis,-1)),((a,0),(g,0),r,r,(dis,0),(gis,-1)))
      durss:      ((8,16,16),(8.,16),(8,8,8))
      accentss:   ((>,~,~))
    voice3:
      vtype:      repeat
      mPitOctsss: (((a,0),(g,0),(dis,0),r,(gis,-1)),((a,0),(g,0),r,r,(dis,0),(gis,-1)))
      durss:      ((16,8.))
      accentss:   ((~,>,>),(>,>,~,~,~))
      register:   (g,-1)
      durval:     int 1024

# trial:  first pass without param to tie voices together
homophony:
  common:
    tempo:       (100,4)
    key:         c major
    changeclefs: int 3
    instr:       acoustic grand
    time:        (4,4)
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
    register:    (c,0)
    accentss:    ((>,>,~,~),(~,>,>),(>,>,>,>))
    durss:       ((8),(16,16),(4),(8,8),(16,16,16,16))
    mPitOctsss:  (((b,0),(e,0),(a,0),(d,0),r,(g,0),(c,0),(f,0),(ais,0),(cis,0),r,(dis,0),(fis,0),(gis,0)),
                  ((b,0),(e,0),r,(a,0),(d,0),(g,0),(c,0),(f,0),(ais,0),(cis,0),(dis,0),r,(fis,0),(gis,0)))
  section:
    stype:      homophony
    reps:       int 4
    uniformAcc: !
    uniformDyn: mp
    vesmods:    (uniformAccs,uniformDyns)
    common:
      vtype:    canon
      durval:   int 512
    voice1:
      rotval:   int 0
    voice2:
      rotval:   int 0
    voice3:
      rotval:   int 0
    voice4:
      rotval:   int 0

# expand mpitOcts to allow for chords, durss to allow for tuplets
experimental:
  common:
    tempo:       (100,4)
    key:         c major
    changeclefs: int 3
    instr:       acoustic grand
    time:        (4,4)
    scale:       (c,cis,d,dis,e,f,fis,g,gis,a,ais,b)
    register:    (c,0)
    accentss:    ((>,>,~,~),(~,>,>),(>,>,>,>))
  section:
    stype:      homophony
    reps:       int 1
    common:
      vtype:      repeat
      durval:     int 512
      reps:       1
      mPitOctsss: (((b,0),r,((a,0),(f,0))))
      durss:      ((8),(16,16),(4),(8,(3,2,8,(16,8,16,16,16)),4)))
    voice1:
    voice2:
    voice3:
    voice4:
