name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.4'
        cabal-version: '3.4'

    - name: Cache
      uses: actions/cache@v2.1.3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-ghc-8.8.4-stack

    - name: Install dependencies
      run: |
        stack build --only-dependencies
    - name: Build
      run: stack build
    - name: Run tests
      run: |
        wget -q https://lilypond.org/download/binaries/linux-64/lilypond-2.22.0-1.linux-64.sh
        sh lilypond-2.22.0-1.linux-64.sh --batch
        stack test
